MAX_VALIDATORS_PER_COMMITTEE = 2 ** 11
SYNC_COMMITTEE_SIZE = 2 ** 9
BYTES_PER_LOGS_BLOOM = 2 ** 8
MAX_EXTRA_DATA_BYTES = 2 ** 5
SLOTS_PER_HISTORICAL_ROOT = 2**13
HISTORICAL_ROOTS_LIMIT = 2**24
EPOCHS_PER_ETH1_VOTING_PERIOD = 2**6
VALIDATOR_REGISTRY_LIMIT = 2**40
EPOCHS_PER_HISTORICAL_VECTOR = 2**16
EPOCHS_PER_SLASHINGS_VECTOR = 2**13
JUSTIFICATION_BITS_LENGTH = 4
SLOTS_PER_EPOCH = 2**5
MIN_EPOCHS_TO_INACTIVITY_PENALTY = 2**2

FAR_FUTURE_EPOCH = 2 ** 64 - 1
